<?php

use Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException;

/**
 * Captures a screen shot using PhantomJS by calling the program.
 *
 * @param string $url
 *   The ULR/http(s) to render the screen shot from.
 * @param string $filename
 *   The filename to store the file as in the destination.
 * @param string $element
 *   The id of the DOM element to render in the document.
 *
 * @return bool
 *   Returns TRUE if the screen shot was taken else FALSE on error.
 *
 * @throws PhantomJSCaptureException
 *
 * @todo: provide this as a service
 */
function phantomjs_capture_screen($url, $filename, $element = NULL) {
  $config = \Drupal::config('phantomjs_capture.settings');

  $binary = $config->get('binary');
  $destination = $config->get('destination');

  if (!file_exists($binary)) {
    throw new FileNotFoundException($binary);
  }

  // Get absolute path to PhantomJS script and the destination file.
  $script = realpath($config->get('script'));
  $destination = \Drupal::service('file_system')->dirname($destination . '/' . $filename);

  // Run PhantomJS to create the screen shot.
  $output = array();

  if ($element) {
    exec($binary . ' ' . $script . ' "' . $url . '" ' . $destination . ' ' . escapeshellarg($element), $output);
  }
  else {
    exec($binary . ' ' . $script . ' "' . $url . '" ' . $destination, $output);
  }

  // Check that PhantomJS was able to load the page.
  if ($output[0] == '500') {
    return FALSE;
  }

  return TRUE;
}
